### PR TITLE
Include Wales in the intro text

### PR DESCRIPTION
**Pull request by usr110**
Relevant issue: https://github.com/npct/pct-shiny/issues/753

### CODE REVIEW

**Comment by nikolai-b** [comment]
@usr110 looks like it is used in the region stats and a few other places: https://github.com/npct/pct-shiny/search?q=%22for+England%22&unscoped_q=%22for+England%22

Is it worth fixing them all now?

**Comment by usr110** [comment]
Good point @nikolai-b, thanks.

It's something that @JDWoodcock might have a view on. What do you think?

**Comment by JDWoodcock** [comment]
ideally yes but if lack of time then the most visible could be prioritised. In some of the case studies it might be complicated as the work was done before Wales was added @RachelAldred @AnnaGoodman1

**Comment by AnnaGoodman1** [comment]
i think most of yourexamples are fine, nikolai, either already say 'and wales' or else are truly england only (schools). I can't see any very problematic ones, except the one Ali fountd

**Comment by nikolai-b** [comment]
Sorry to ask again but is the about section of the website ok as it is?

http://pct.bike/tabs/about.html

> Different visons [sp] of the future are represented through various scenarios of change,including the Department for Transport’s draft Cycling Delivery Plan target to double cycling in a decade and the more ambitious ‘Go Dutch’ scenario, whereby cycling levels are reached in England (allowing for English hilliness and trip distances).

**Comment by JDWoodcock** [comment]
actually it doesnt read well - thanks for noticing . I suggest this (changing spelling mistake, adding subclause, and england change

Different visions of the future are represented through various scenarios of change, including the Department for Transport’s draft Cycling Delivery Plan target to double cycling in a decade and the more ambitious ‘Go Dutch’ scenario, whereby cycling levels equivlaent to the Netherlands are reached in England and Wales (allowing for English and Welsh hilliness and trip distances).

**Comment by AnnaGoodman1** [comment]
thanks @nikolai-b , have amended the text htere

**Comment by usr110** [comment]
Brilliant, thanks @AnnaGoodman1 @nikolai-b and @JDWoodcock 

Merging it now.

**Pull request merged**
