### PR TITLE
Update about_body.html

### PR DESCRIPTION
**Pull request by usr110**
Update links for personal page of mine and @JDWoodcock

### CODE REVIEW

**Review by Robinlovelace — APPROVED** [review]

**Comment by Robinlovelace** [comment]
Good tweaks, worth updating the other links with http:// not https:// URLs?

**Review by Robinlovelace — COMMENTED** [review]
We could use this as an opportunity to update all URLs. No other ones are broken but good to do it in one go, e.g. for Anna's: https://github.com/npct/pct-shiny/pull/882/files#diff-0b70f2be0647d854c713fc5e284c2d845907c22fa6d5318223d260acd2414090L51

**Comment by usr110** [comment]
> Good tweaks, worth updating the other links with http:// not https:// URLs?

Thanks for reviewing. I don't mind either way. We just need to make sure that none of the links uses HTTPS then. I can see that the blog entry, for instance uses it.

**Comment by usr110** [comment]
> We could use this as an opportunity to update all URLs. No other ones are broken but good to do it in one go, e.g. for Anna's: https://github.com/npct/pct-shiny/pull/882/files#diff-0b70f2be0647d854c713fc5e284c2d845907c22fa6d5318223d260acd2414090L51

Indeed. Not following what you said by Anna's link though. It seems to work fine at my end.

**Comment by mvl22** [comment]
> We just need to make sure that none of the links uses HTTPS then. I can see that the blog entry, for instance uses it.

If a site works under HTTPS, these days you should be linking to that instead of the HTTP equivalent. Very little of the web is now on HTTP, because it produces a browser warning.

**Comment by Robinlovelace** [comment]
Let's update all of them then :+1:

**Review by Robinlovelace — CHANGES_REQUESTED** [review]
Should be https throughout.

**Comment by usr110** [comment]
> if a site works under HTTPS, these days you should be linking to that instead of the HTTP equivalent. Very little of the web is now on HTTP, because it produces a browser warning.

Good point 👍

**Comment by nikolai-b** [comment]
:wave: the checks are failing as the github workflow is broken.  I didn't fully understand the docs and thought I needed to have the workflow in `master` before it would run but I was wrong and I've fixed it in #883 so you can ignore the build error here, sorry.

**Comment by usr110** [comment]
> 👋 the checks are failing as the github workflow is broken. I didn't fully understand the docs and thought I needed to have the workflow in `master` before it would run but I was wrong and I've fixed it in #883 so you can ignore the build error here, sorry.

Got it. Many thanks 👍

**Review by Robinlovelace — APPROVED** [review]

**Comment by Robinlovelace** [comment]
Good job on the updates Ali, the failing tests have nothing to do with this cosmetic and good PR so merging.

**Pull request merged**
