### PR TITLE
Update production

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Let's see if it deploys correctly...

**Comment by nikolai-b** [comment]
[Looks good](https://app.circleci.com/pipelines/github/npct/pct-shiny/26/workflows/5e422675-accc-4ee9-bac6-a07667125719/jobs/1480/parallel-runs/0/steps/0-102) so far

**Comment by Robinlovelace** [comment]
Agreed, looks good to me. @AnnaGoodman1 please could you take a quick look when you get a chance? Many thanks.

**Comment by AnnaGoodman1** [comment]
looks good, thanks all

**Pull request merged**
