### PR TITLE
Changes to make the site accessible on mobile

### PR DESCRIPTION
**Pull request by Robinlovelace**
On small devices the tab names are too large,
FAQ and How does it work can fit nicely into
one tab.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Can others check the look and feel of the site under this branch? Anything to make the interface/look more steamlined sounds good, will give it a play.

**Comment by nikolai-b** [comment]
Ha, I wasn't ready to open a PR as I hadn't finished testing but :runner: go for it @Robinlovelace .

I'll keep playing and comment back here when I'm happy.  My feeling is the site should work on mobile with little effort and that should be something we aim for.

**Comment by nikolai-b** [comment]
This is a fairly hefty change would be great to get it in with a bit of testing (it works fine on mine as far as I can tell).

**Comment by Robinlovelace** [comment]
Great stuff - merging and pushing to geo8. We can always revert this. Great work @nikolai-b

**Pull request merged**
