### PR TITLE
Make the PCT link more clearer

### PR DESCRIPTION
**Pull request by nikolai-b**
Refs #592
@usr110 What do you think?

### CODE REVIEW

**Comment by usr110** [comment]
@nikolai-b Looks great, thanks. Just one thing I'd add: would it be easier to have a same look and feel as the current text? (black fonts and more spacing between the text and the icon)
Like this:
image

**Comment by usr110** [comment]
@nikolai-b Have another thought: how about if we change the javascript function to display the text as always here: https://github.com/npct/pct-shiny/blob/master/regions_www/www/la-map-resources/leaflet-control-credits.js

Any idea how to go about it?

**Comment by usr110** [comment]
Updated the `js` code here: https://github.com/npct/pct-shiny/commit/f95223781253aa68da008faf0b81c2091bd6f801

We can close this `PR`. What do you think @nikolai-b

**Comment by usr110** [comment]
You can see the change on the [test-server](http://npct0.vs.mythic-beasts.com/la-map.html). If you are happy with it, I will push it to the production branch.

**Comment by nikolai-b** [comment]
@usr110 it is better but now the image isn't a link.  I don't like the link being black text but I can change the spacing in this pull if you prefer.

**Pull request closed without merging**
