### PR TITLE
Use slc instead of sivalue_heat for route_network. Fix #775

### LINKED ISSUE #775: Pop-up for route networks under a specific case do not show up
Hi, 

Just found another bug - which might be an artifact of the fix for #773.

The popup for route networks stop displaying when you follow these steps:

1) Swich purpose to `School`
2) Select `Go Cambridge` scenario
3) Select `route network (clickable)` flow
4) Change purpose back to `Commute` - which changes the default `scenario` to `commute`
5) Now `route network (clickable)` is working fine - thanks to the fix in #773, however, 
6) Switch `scenario` to any other than `census`, the popups for `route network (clickable)` will not work.

I know @nikolai-b you've been working quite diligently over such issues, and I have added a new one in your bucket. I think I may have some time later today to work on this one.

### PR DESCRIPTION
**Pull request by usr110**
As the description says. Relevant issue: #775.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Thanks for the quick fix @usr110. Will test later today.

**Comment by Robinlovelace** [comment]
Testing on this branch, the route network popup is working:

image

**Comment by Robinlovelace** [comment]
Furthermore when you go back to a different scenario or Commuting, it still works. Great fix @usr110 

image


Fixed, cannot see any regressions, so planning to merge this.

**Comment by usr110** [comment]
Thanks for testing and merging @Robinlovelace !

**Pull request merged**
