### PR TITLE
Lazy load

### PR DESCRIPTION
**Pull request by nikolai-b**
Re #781

- Speed up freeing memory: Only ever remove one data file at a time 
- Load the straight lines and routes only if needed

This is much faster for me :smile:

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Fantastic work. No time to test this week, should get on it Tuesday. Could you provide a rough estimate of how much faster? And what kind of usage cycle to you use, many regions I assume. By the sounds of it this + #789 should allow us to fix #781.

**Comment by nikolai-b** [comment]
Speed up depends on a few too many things. If you are changing region and are viewing lines and the `loaded_data` isn't full then this provides no speeds up. If you have no lines or route network selected and `loaded_data` is full and R gets confused and the `while` loop removes everything in `loaded_data` then it could be a +15s speed up.

**Comment by nikolai-b** [comment]
I've added loading and ordering time logging.  In doing that I notice we are doing a the most expensive operations twice (loading a region and sorting) so I've also fixed that.

From https://github.com/npct/pct-shiny/pull/789#issuecomment-527648285 

So currently London MSOA commute with lines or routes takes (on my laptop) ~ 8.3 s to load the Rds files and an additional ~ 2.3 s to order and plot the lines.

With this PR if no lines are selected, or route network then we don't load the route Rds files so the London load time is reduced to ~ 0.2 s (pretty fast).  If we are loading the lines / routes Rds files then with this PR we now save ~ 4 s by only loading the region once and sorting the lines once.  I've tested locally but really make sense for this to be tested again as it changes a few things.

**Comment by Robinlovelace** [comment]
Excellent and important work by the sounds of it @nikolai-b - will test now with an aim to get this on production ASAP.

**Comment by Robinlovelace** [comment]
For testing, it's ~9 seconds on my computer for London. Before this MR:

Peek 2019-09-04 10-41

**Comment by Robinlovelace** [comment]
After the fix it is much faster, ~3s I counted, output from new code:

```
[1] "Loading region london for msoa commute took 0.132 s"
[1] "Loading region london for msoa commute took 0.056 s"
[1] "Plotting top 30 none took 0.01 s"
```

Results:

Peek 2019-09-04 10-45

**Comment by Robinlovelace** [comment]
One question @nikolai-b, when I load the clickable route network I get this output:

```
[1] "Plotting top 30 straight_lines took 3.021 s"
[1] "Plotting top 30 route_network took 0.876 s"
```

Is that right?

**Comment by nikolai-b** [comment]
> One question @nikolai-b, when I load the clickable route network I get this output:
> 
> ```
> [1] "Plotting top 30 straight_lines took 3.021 s"
> [1] "Plotting top 30 route_network took 0.876 s"
> ```
> 
> Is that right?

As in the route network is much faster?  I'm not sure what your asking.

route

**Comment by Robinlovelace** [comment]
I meant are the statements correct. I don't think they are. When you load the route network I think it's incorrect that shiny is `Plotting top 30 route_network took 0.876 s`. Also, I was surprised to see the route network was that much faster. Looking at the route network timings in your gif make more sense.

**Pull request merged**
