### PR TITLE
Add old version of app

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
For @nikolai-b and others to see what has changed in the actual app code without the distractions of the other 22k changed lines of code in https://github.com/npct/pct-shiny/pull/596 . This PR is not designed to be merged.

**Comment by Robinlovelace** [comment]
In summary, just over 1000 lines of code have changed, which I confess is a large diff, but not many of them seem major or could be expected to break the test server.

**Comment by Robinlovelace** [comment]
Also added init.R and pct_shiny_funs.R (previously pct-shiny-funs.R) - I think that's all the R files that have changed now.

**Comment by nikolai-b** [comment]
Thanks @Robinlovelace.  Sadly this isn't very useful as it wasn't the changes merged in #596 and misses lots of important things which need to be reviewed.

**Comment by nikolai-b** [comment]
@Robinlovelace if this isn't to be merged than it is dangerous to have it open as a pull request, would you mind closing it?

Fine to do it from a separate repo but if this not intended to be merged then it doesn't need to be here

**Comment by Robinlovelace** [comment]
Didn't mean to reopen it.

**Comment by nikolai-b** [comment]
:sunglasses:

**Comment by Robinlovelace** [comment]
Dangers of checking github from a mobile device..

**Pull request closed without merging**
