### PR TITLE
Update about page with references

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by nikolai-b** [comment]
👍

**Comment by usr110** [comment]
Would be nice if you @Robinlovelace use `target="_blank"` in all links

**Comment by AnnaGoodman1** [comment]
added 'target="_blank"', looks good to me

**Comment by usr110** [comment]
Great work @AnnaGoodman1 !

**Comment by Robinlovelace** [comment]
Thanks Anna - didn't see you'd already fixed it before pushing this!
https://github.com/npct/pct-shiny/commit/e4a500a666f90cd2ce029a78323d4200127f9173

Closing this one as there's a merge conflict now as we both edited the same lines of text on different forks.

**Pull request closed without merging**
