### PR TITLE
Rename cols

### PR DESCRIPTION
**Pull request by nikolai-b**
This updates shiny inline with the changes in https://github.com/npct/pct-load/pull/34
Suffolk is using the new column names so this change should work there (but no where else)
If you get time can you test it for Suffolk and then merge this?

P.S. @Robinlovelace I've removed you folder move from this branch as it isn't a rename and I think it was included by accident (sorry, you might have to drop your local branch to pull this down...)

### CODE REVIEW

**Comment by Robinlovelace** [comment]
@nikolai-b great work, will test then merge now.

**Comment by Robinlovelace** [comment]
@nikolai-b have you tested it? On my machine in the rename-cols branch I get 

```
Warning in min(values) : no non-missing arguments to min; returning Inf
Warning in min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
Warning in max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
Warning: Error in round: non-numeric argument to mathematical function
Stack trace (innermost first):
    72: sprintf
...
```

**Comment by Robinlovelace** [comment]
Apologies Nikolai - I just didn't pull from the new branch before testing. When I did, it words :8ball:

**Comment by Robinlovelace** [comment]
@nikolai-b pushed to production, seems to be working.

**Comment by nikolai-b** [comment]
Have you rebuilt all the regions? I was finding a few crash.

**Comment by Robinlovelace** [comment]
Yes I thought I did. Which crash?

**Comment by Robinlovelace** [comment]
- we should have an automated test for this - should be quite easy with runApp()

**Pull request merged**
