### PR TITLE
Code tidy

### PR DESCRIPTION
**Pull request by nikolai-b**
@Robinlovelace and @usr110 this uses `snake_case` as standard and also fixes up a few things (see https://github.com/npct/pct-shiny/commit/c534d6 for the actual changes that aren't just code style)

### CODE REVIEW

**Comment by usr110** [comment]
Great improvements, @nikolai-b 
There is however one little change I'd suggest - after testing it.
https://github.com/npct/pct-shiny/pull/264/commits/c534d628583bf5e85f67c303c9a29a2a0423efc4#diff-0dff37e04377b42623d6bf034dac14bfR26

doesn't work on Windows. 

Revert it to its earlier version:

https://github.com/npct/pct-shiny/pull/264/commits/c534d628583bf5e85f67c303c9a29a2a0423efc4#diff-0dff37e04377b42623d6bf034dac14bfL23

Rest is all fine.

**Comment by nikolai-b** [comment]
@usr110 thanks very much for the feedback!  I was missing an amend, should be fixed now, sorry

**Comment by usr110** [comment]
Yes, that seems to work. Thanks @nikolai-b.

**Comment by Robinlovelace** [comment]
Will test and pull asap - thanks @nikolai-b

**Comment by Robinlovelace** [comment]
Thanks @usr110  - you got their first. Was going to ask about a few things (with nikolai now) first but nothing major. Great to have tidy, consistent code!

**Pull request merged**
