### PR TITLE
Release

### PR DESCRIPTION
**Pull request by nikolai-b**
@AnnaGoodman1 said we have sign off to release this version to production.

@usr110 and @Robinlovelace there aren't any of your commits in this PR but I think it is good practise to give you opportunity to check the changes before we push them live so if you could review this PR that would be great.  The same goes for @AnnaGoodman1 to show your happy with releasing this. 

Thanks.

### CODE REVIEW

**Comment by AnnaGoodman1** [comment]
Yes please, thanks!

**Comment by AnnaGoodman1** [comment]
@nikolai-b : thanks, but seems to now be an error on main PCT?! unless a temporary syncing thing...

image

**Comment by Robinlovelace** [comment]
Working now: http://www.pct.bike/m/?r=west-yorkshire

**Comment by AnnaGoodman1** [comment]
yes indeed, phew!

**Comment by usr110** [comment]
Slightly late here but thanks for keeping me in the loop @nikolai-b. Great work @AnnaGoodman1 !

**Pull request merged**
