### PR TITLE
Revert "Update to master"

### PR DESCRIPTION
**Pull request by Robinlovelace**
Reverts npct/pct-shiny#293

### CODE REVIEW

**Comment by usr110** [comment]
Why revert?

**Comment by Robinlovelace** [comment]
To give people a chance to comment - this is the workflow - needs sign-off.

**Comment by Robinlovelace** [comment]
Thanks @usr110 - This has been checked and pushed to production. Please allow time for others to test the test version before closing these PRs in future.

**Comment by usr110** [comment]
Agreed @Robinlovelace. I assume you're sorting out the discripancy between the `master `and the `production `branch?

**Comment by Robinlovelace** [comment]
Fair assumption.

**Pull request merged**
