### PR TITLE
Update production

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Please @nikolai-b or @usr110 accept this PR if it seems good to go.

It has some bug fixes - e.g. https://github.com/npct/pct-shiny/issues/436 - so keen to update pct.bike.

**Comment by Robinlovelace** [comment]
Bump @nikolai-b

**Comment by nikolai-b** [comment]
Do we want all trips on production?
https://github.com/npct/pct-shiny/issues/435#issuecomment-260134143 @JDWoodcock thinks there is much more work before it should go live.  Also doesn't @AnnaGoodman1 have quite few questions #439 about the new data?

**Comment by JDWoodcock** [comment]
no please do not push all trips to production ! @Robinlovelace @nikolai-b @audev

**Comment by JDWoodcock** [comment]
no please do not push all trips to production ! @Robinlovelace @nikolai-b @audev

**Comment by nikolai-b** [comment]
Actually it looks like this has happened 25 days ago https://github.com/npct/pct-shiny/pull/426

http://www.pct.bike/greater-manchester/ has all trips.

@JDWoodcock if we really don't want in on production we can hide it on testing, merge that into production and then re-enable it.  It would be very simple.  Are we happy with the new builds going onto production?

**Comment by JDWoodcock** [comment]
@nikolai-b @nikolai-b please remove it from the production version as a  matter of urgency.
@AnnaGoodman1 @RachelAldred 
I have not checked the new builds, but they definitely need to be checked before they go live

**Comment by Robinlovelace** [comment]
@JDWoodcock @audev you need to remove the GM layers files from the production branch. I suggest a separate `gm_layers` branch is set-up to avoid this happening - we have been working in this way, testing updates on `master` and pushing to `production` incrementally for a long time so I assumed when these updates were pushed the desire was for them to go into production as has happened with all other updates pushed to `master`. Happy to look at this but it won't be until Wednesday so suggest @audev or @nikolai-b does it if either get a spare moment.

**Comment by JDWoodcock** [comment]
@Robinlovelace I understand that we agreed that someone from the academic team in addition to you has to sign things off before they are pushed

**Pull request closed without merging**
