### PR TITLE
Add the PCT impact report

### LINKED ISSUE #863: Impact report 2020
From @RachelAldred 

> The 2020 PCT impact report – it’s here: [2020-pct-impact-report.pdf](https://github.com/npct/pct-shiny/files/5592634/2020-pct-impact-report.pdf)
> 
> I’d suggest on the Manual page, under ‘Other reports’ – it could go above ‘Use of the PCT (Nov 2019)’ perhaps labelled ‘Use of the PCT (Nov 2020)’ We can leave the old version up so people can compare if they want. Once it’s online it’ll be easier for our various universities to point to it as part of their demonstration of ‘impact’.

### PR DESCRIPTION
**Pull request by nikolai-b**
Resolves #863 

Screenshot from 2020-11-24 20-57-12

### CODE REVIEW

**Review by Robinlovelace — APPROVED** [review]

**Comment by Robinlovelace** [comment]
Looks good, not tested on the test server yet but assuming that's looking good we can get this on production asap. Great work @nikolai-b !

**Comment by RachelAldred** [comment]
Hello @nikolai-b & @Robinlovelace - not sure if I am looking at the wrong thing but I can't see it on the website yet - is there anything I need to check/do? Thanks :)

**Comment by Robinlovelace** [comment]
Should be on the test website. We need to update the production branch, should have seen that. I plan to merge this tomorrow morning (unless someone else gets there first) by which point it should be up there: https://github.com/npct/pct-shiny/pull/865

Apologies for the delay.

**Comment by nikolai-b** [comment]
It is live now @RachelAldred and @Robinlovelace

**Comment by Robinlovelace** [comment]
:tada:

**Comment by RachelAldred** [comment]
Thank you!

**Pull request merged**
