### PR TITLE
Remove school NAs on Rds load

### PR DESCRIPTION
**Pull request by nikolai-b**
@AnnaGoodman1 can we not avoid the `school` data and use the `school_download` data instead?

That would mean any change in the downloads would always be reflected in the interface (and vice versa).  Having two different files leads the the possibility that they become out of sync.

### CODE REVIEW

**Comment by AnnaGoodman1** [comment]
okay yes, I can see that would be an advantage.  but this is not yet quite right, the correct number to impute varies by variable for d and z files (rnet is ok):


d files |  
all | NA -> 3
bicycle | NA -> 3
foot | NA -> 3
car | NA -> 3
govtarget_slc | NA -> 3 + govtarget_sic
govtarget_slw | NA -> 3 + govtarget_siw
govtarget_sld | NA -> 3 + govtarget_sid
dutch_slc | NA -> 3 + dutch_sic
dutch_slw | NA -> 3 + dutch_siw
dutch_sld | NA -> 3 + dutch_siw
  |  
z files |  
all | NA -> 1.5
bicycle | NA -> 1.5
foot | NA -> 1.5
car | NA -> 1.5
govtarget_slc | NA -> 1.5 + govtarget_sic
govtarget_slw | NA -> 1.5 + govtarget_siw
govtarget_sld | NA -> 1.5 + govtarget_sid
dutch_slc | NA -> 1.5 + dutch_sic
dutch_slw | NA -> 1.5 + dutch_siw
dutch_sld | NA -> 1.5 + dutch_siw
  |  
rnet files |  
bicycle | NA -> 1.5
govtarget_slc | NA -> 1.5
dutch_slc | NA -> 1.5

**Comment by AnnaGoodman1** [comment]
Thanks @nikolai-b, This looks like it should work but - ugh - it is still giving me error messages: however I am confident this will work, so I have changed the content of pct-outputs-regional-R/school/lsoa/isle-of-wight/ to now be the correct input file, i.e. having missing values that can be imputed
 

Warning: Error in [<-.data.frame: 'value' is the wrong length
Stack trace (innermost first):
    58: [<-.data.frame
    57: [<- [C:\Users\Anna Goodman\Dropbox\GitHub\pct-shiny\regions_www\m/server.R#326]
    56: observerFunc [C:\Users\Anna Goodman\Dropbox\GitHub\pct-shiny\regions_www\m/server.R#326]
     1: runApp
Warning: Error in [<-.data.frame: 'value' is the wrong length
Stack trace (innermost first):
    58: [<-.data.frame
    57: [<- [C:\Users\Anna Goodman\Dropbox\GitHub\pct-shiny\regions_www\m/server.R#326]
    56: observerFunc [C:\Users\Anna Goodman\Dropbox\GitHub\pct-shiny\regions_www\m/server.R#326]
     1: runApp
ERROR: [on_request_read] connection reset by peer

**Comment by nikolai-b** [comment]
@AnnaGoodman1 thanks again, sorry I wasn't sub-selecting the base by the NA index,
i.e. with 
govtarget_slc | NA -> 3 + govtarget_sic

I was trying to replace the NA's with 3 + all the govtarget_sic, instead of only the govtarget_sic with the same index as the govtarget_slc's with NA

Hope that makes sense.

**Comment by AnnaGoodman1** [comment]
ok great. and yes, that makes sense

**Pull request merged**
