### PR TITLE
Pin data sha

### PR DESCRIPTION
**Pull request by nikolai-b**
For changes see commit messages :wink:

### CODE REVIEW

**Comment by Robinlovelace** [comment]
@nikolai-b thanks but you're editing computer generated files. Please edit the code that creates `regions_www/region/server.R` rather than the file itself. The code that creates `regions_www/region/server.R` can be found here: https://github.com/npct/pct-load/blame/master/load.Rmd#L683

**Comment by nikolai-b** [comment]
@Robinlovelace does https://github.com/npct/pct-load/pull/40 not address this?
Even with it we need to change the current files

**Comment by Robinlovelace** [comment]
To confirm: would I change the sha from [what it is at the moment](https://github.com/npct/pct-shiny/commit/59c84c5a1d67a312654697c966ccc54cb6fe0fef) to `013e828` to update the data to the latest commit - here https://github.com/npct/pct-data/commit/a4238010904140fd79e2bf6d854bb82ac013e828 ?

**Comment by nikolai-b** [comment]
yes

**Comment by Robinlovelace** [comment]
OK - that's a more failsafe approach and sounds good. And btw yes it looks like your PR in pct-load solves the issue, didn't see that sorry. You've tested it right?

**Comment by nikolai-b** [comment]
Shiny loads and runs.  Might be worth holding off merging till I add an environment variable to stop the data download and the init script running on production.

**Comment by Robinlovelace** [comment]
OK will do.

Want it to plug and play on laptops also but that shouldn't be a problem. Can you envisage any issues on Windows/non git installed machines?

**Comment by nikolai-b** [comment]
https://github.com/npct/pct-shiny/commit/aa4482d1c31661af1ae50eab0efd9b06b75d3ead stops the `init.R` running on production so this is ready to merge.

**Comment by Robinlovelace** [comment]
:+1:

**Pull request merged**
