### PR TITLE
Update about

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
@AnnaGoodman1 @RachelAldred @JDWoodcock please take a look - much better linked-up to blog, official report and podcast I think now.

**Comment by Robinlovelace** [comment]
No response from others so planning to merge.

**Comment by JDWoodcock** [comment]
sorry for slow response but not sure this goes here

**Comment by Robinlovelace** [comment]
Done by @nikolai-b in #588 - please communicate before acting on issues assigned to other people.

**Pull request closed without merging**
