### PR TITLE
Exclude current region from being highlighted when flows are displayed

### PR DESCRIPTION
**Pull request by usr110**
@Robinlovelace would appreciate it you test it.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Still not working for me:

image

**Comment by Robinlovelace** [comment]
Apologies - was using an old branch. The specific problem is fixed. Great work.

However, there is a new problem: the route network layers do not appear when you click on a new region now:

image

Any ideas?

Can open a new issue or we can just work on it here for convenience (my suggestion).

**Comment by Robinlovelace** [comment]
Also it doesn't seem to want to change region when route network is selected...

**Comment by usr110** [comment]
Thanks Robin for the testing. The route-network problem was caused by @nikolai-b's commit: https://github.com/npct/pct-shiny/commit/a7860aa3723f4c5a619851352c77f87a494d5e36

I have reverted it. See it resolves it.

**Comment by Robinlovelace** [comment]
Still not working for the LSOA layer for me...

**Comment by Robinlovelace** [comment]
Please test the LSOA and MSOA layer and switching back and forth to regions when all layers are selecting. Please tag me when you want them tested.

**Comment by usr110** [comment]
Have fixed all the outstanding issues (including this one: https://github.com/npct/pct-shiny/issues/557#issuecomment-286752568). Please test again @Robinlovelace

**Comment by Robinlovelace** [comment]
Looking very slick for all layers and regions I've tested Ali. Great work.

**Comment by usr110** [comment]
thanks @Robinlovelace 👍

**Pull request merged**
