### PR TITLE
Combine national downloads

### PR DESCRIPTION
**Pull request by usr110**
WIP - please don't merge

Combined national download page, for the landing page. Relevant issue: https://github.com/npct/pct-shiny/issues/785

### CODE REVIEW

**Comment by nikolai-b** [comment]
Sorry for the slow review!  The `pct-shiny/regions_www/tabs/download_national.html` needs to be a full HTML file starting with

```html
<!DOCTYPE html>
<html xmlns="https://www.w3.org/1999/xhtml">
```

and also including the navigation.  I can update it if you like?

**Comment by usr110** [comment]
No worries and thanks @nikolai-b 

Re missing `HTML` tags, I've added them here: https://github.com/npct/pct-shiny/pull/796/commits/9834170e89df42f9c155887de021e21903abf6cb

Hope it's all fine now.

**Comment by nikolai-b** [comment]
When I view the page it looks like this:

Screenshot-2019-10-13 The Propensity to Cycle Tool - National Data(1)

Is that what you intended?

Sorry there isn't an easy way for us to develop it locally yet :cry: .  I've pushed it to the staging server so you can see and edit (but any merges will remove it)

**Comment by Robinlovelace** [comment]
Is this PR still alive @nikolai-b and @usr110 ? I've converted it to a draft having seen the latest comment from Nikolai.

Many thanks Ali, looks like it's an improvement overall, will be great to get this out there.

**Pull request closed without merging**
