### PR TITLE
Update production to include local-authority map

### PR DESCRIPTION
**Pull request by usr110**
Add local authority map on the live server.

Apart from this commit https://github.com/npct/pct-shiny/commit/4d720c6d5d983c9ce240c4563635dd54fcfb70eb I believe we can merge the two branches

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Lots of commits here - what's an ETA for this being ready @usr110? Will be great to get this out there.

**Comment by Robinlovelace** [comment]
Hi @usr110 next time please tag me with @robinlovelace next time you push changes to production.

**Comment by usr110** [comment]
@Robinlovelace Good point. You weren't involved in the local authority map, hence weren't consulted. But I take it that it's a good practice to involve the wider team when important changes are made to the live server.

**Comment by Robinlovelace** [comment]
As a process, are you happy to tag me and in general allow me to do accept after consulting with team? In this case I understand why you did that, but please be careful to check other unrelated commits don't get mixed up. Cheers!

**Comment by usr110** [comment]
> As a process, are you happy to tag me and in general allow me to do accept after consulting with team?

Sure. Let's stick to a protocol. Whoever creates a `PR`, tag at least the three of us (you, I and Nikolai). An examples where it wasn't done, for instance: https://github.com/npct/pct-shiny/pull/528

>  but please be careful to check other unrelated commits don't get mixed up

And what are those?

**Comment by Robinlovelace** [comment]
This one: https://github.com/npct/pct-shiny/pull/581/commits/4d720c6d5d983c9ce240c4563635dd54fcfb70eb

Yes - I think in organisations it's generally the role of lead dev to push to master. The protocol agreed by others was as follows, so let's try to stick to that: 


```
Make changes on test branch, put in PR for lead dev or other to test and then accept if good

Provide time (a couple of days I suggest) for others to test new feature.

Put in a Pull request tagging all

Lead dev accepts PR after green light from team
```

**Comment by usr110** [comment]
Re https://github.com/npct/pct-shiny/pull/581/commits/4d720c6d5d983c9ce240c4563635dd54fcfb70eb

See this comment: https://github.com/npct/pct-shiny/pull/581#issue-220191577

Also as soon I merged this `PR`, I reverted your commit here: https://github.com/npct/pct-shiny/commit/918618a5aa330bf145edc2a3381a84af303ba11f

So please do double check.

**Comment by Robinlovelace** [comment]
Yes I see now it was @nikolai-b. I did double check and commented on the process [here](https://github.com/npct/pct-shiny/commit/20101cf940bd5717bafb6ae34204c3cba19e63c7).

In summary: double check with others (probably best me first) before pushing to production!

**Comment by Robinlovelace** [comment]
Good work on reverting that commit btw - please keep me in the loop next time though.

**Comment by usr110** [comment]
> Yes I see now it was @nikolai-b. I did double check and commented on the process here.

Good! Just a suggestion, please do this check before you send an email to James as well.

**Comment by Robinlovelace** [comment]
Will do - apologies for blaming you again Ali - was because you had all the most recent commits. Great communications in any case that has hopefully led to a better process.

**Comment by usr110** [comment]
Thanks Robin 👍

**Pull request merged**
