### PR TITLE
Update manual.Rmd

### PR DESCRIPTION
**Pull request by Robinlovelace**
Clarify how to edit the Manual.

### CODE REVIEW

**Comment by nikolai-b** [comment]
Ah, thanks!

**Comment by nikolai-b** [comment]
And nice one for persisting with getting Rmarkdown in, looks like a right pain but nearly there!

**Comment by Robinlovelace** [comment]
:+1: no worries - I also wish it were less hacky and there are definitely ways to make it so. Like not having the Manual as an entire new tab in the pct but I suspect that wouldn't go down so well in some quarters ;-)

**Comment by nikolai-b** [comment]
So to be clear we are meant to run the R code at the bottom
https://github.com/npct/pct-shiny/commit/f6af9ddfeb7ced753a4e1f194959e99f2d8f3eeb#diff-30c30f1ba3c3e88f11836f1ac6aedeccR426
manually?

**Comment by Robinlovelace** [comment]
Ps [this resource](http://rmarkdown.rstudio.com/html_document_format.html) is fantastic for figuring out how Rmd works - a powerful way of generating html and other document files I'm sure you'll agree. Cc @usr110 also as I suspect it may be useful at some later date.

**Comment by Robinlovelace** [comment]
Yes - should make it more clear in the notes - but cheers for asking.

**Comment by nikolai-b** [comment]
Cool, a comment at the top of the file would be nice.

**Comment by Robinlovelace** [comment]
Go for it - that's what this PR does!

**Comment by Robinlovelace** [comment]
Thanks - got there eventually!

**Pull request merged**
