### PR TITLE
first attempt wales govt logo

### PR DESCRIPTION
**Pull request by AnnaGoodman1**

### CODE REVIEW

**Comment by AnnaGoodman1** [comment]
@usr110 , would you be able to check what I've done here and correct it – I'm trying to add the Wales government logo along the bottom, but I can't get them all to go on the same line, it seems to be splitting across lines 

(I had understood the standard width across the web page and each of these six logo seem to have a width of two, so don't really understand why it doesn't fit...presumably there is some way to force it...)

**Comment by Robinlovelace** [comment]
Looks good to me Anna (see below) but only issue is that the Welsh logo seems to be below the others on my set-up. Note I used a local (updated to 3.3.7) version of bootstrap for this but I don't think that would've affected it. @nikolai-b may also see a quick fix - he magically fixed some html formatting issues previously I recall. Will past the html that led to this (basically your code but with relative not absolute links and a local version of bootstrap):

image

**Comment by Robinlovelace** [comment]
```html
<!DOCTYPE html>
<html xmlns="https://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" href="www/icons/favicon.ico">

    <title>Welcome to the Propensity to Cycle Tool (PCT)</title>


    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="//unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.js"></script>
    <script src="www/front_page/map.js"></script>

    <link rel="stylesheet" href="www/front_page/style.css" type="text/css" />
    <link rel="stylesheet" href="www/front_page/map.css" type="text/css" />
    <link rel="stylesheet" href="//unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.css" />
    <style type="text/css">
      pre:not([class]) {
        background-color: white;
      }
    </style>
    <script>
      if (window.hljs && document.readyState && document.readyState === "complete") {
        hljs.initHighlighting();
      };
      $(document).ready(function(){
        $("#includedNav").load("nav.html");
        if (!window.location.href.match(/pct.bike/)) {
          $("body").prepend($("<div>").load("test-banner.html"));
        }
        if (typeof(ga) !== "undefined"){
          $('navbar a').each(function() {
            ga('send', 'event', 'front-nav', $(this).data('value'));
          });
        }
      });
    </script>
    <style type="text/css">
    </style>
    <link rel="import" href="./favicon.html">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
  </head>
  <body>
    <div id="includedNav"></div>
    <div class="container">
      <div class="row-fluid">
        <div class="pull-left plain-margin">
          <div id="map"></div>
        </div>
        <div style="margin-bottom:19px; padding-top:7px;">
          <iframe style="margin-top:19px;" width="425" height="250" src="https://www.youtube.com/embed/58UaVb8ZCrc" frameborder="0" allowfullscreen></iframe>
        </div>

        <div class="container-fluid main-container">
          <p> Welcome to the Propensity to Cycle Tool (PCT) for England, which provides an evidence base to inform cycling investment.</p>
          <p>To run the PCT, first hover over a region on the map on the left to see the regional potential, then click on the region.</p>
          <p>For an introduction to the tool, its use, and the scenarios, please watch the video above.</p>
          <p><strong>What's new :</strong> <a href="https://blog.pct.bike/2017/09/05/new-features/" target = "_blank">Cross-border flows, downloads, Wales &amp more</a>
          </p>
        </div>

        <div style="margin-top:10px; margin-bottom:10px; padding-top:10px; border-top: 1px solid #e7e7e7;">
          <div class="row">
            <div class="col-md-2 col-md-offset-1 text-center logo">
              <a target="_blank" href="http://www.cam.ac.uk/">
                <img src="www/static/01_logos/camuni-logo.png" class="img-responsive" alt="Cambridge University Logo">
              </a>
            </div>
            <div class="col-xs-2 text-center logo">
              <a target="_blank" href="http://www.cedar.iph.cam.ac.uk/">
                <img src="www/static/01_logos/cedar-logo.png" class="img-responsive" alt="Cedar Logo">
              </a>
            </div>
            <div class="col-xs-2 text-center logo">
              <a target="_blank" href="http://www.westminster.ac.uk/">
                <img src="www/static/01_logos/westminster-logo.jpg" class="img-responsive" alt="Westminster University Logo">
              </a>
            </div>
            <div class="col-xs-2 text-center logo">
              <a target="_blank" href="http://www.leeds.ac.uk/">
                <img src="www/static/01_logos/leeds-logo.png" class="img-responsive" alt="Leeds University Logo">
              </a>
            </div>
            <div class="col-xs-2 text-center logo">
              <a target="_blank" href="http://www.gov.uk/government/organisations/department-for-transport/">
                <img src="www/static/01_logos/Department_for_Transport.png" class="img-responsive" alt="DfT Logo">
              </a>
            </div>
            <div class="col-xs-2 text-center logo">
              <a target="_blank" href="http://gov.wales/topics/transport/?lang=en">
                <img src="www/static/01_logos/wales-logo.png" class="img-responsive" alt="Welsh Government Logo">
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- dynamically load mathjax for compatibility with self-contained -->
    <script>
      (function () {
        var script = document.createElement("script");
        script.type = "text/javascript";
        script.src  = "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
        document.getElementsByTagName("head")[0].appendChild(script);
      })();
    </script>
  </body>
</html>

```

**Comment by nikolai-b** [comment]
Hi,

If you all care (fair enough if you don't, the intrinsic of Bootstrap isn't to everyone's taste :smile: )
Bootstrap grids work on 12, so `col-md-6` is taking half the width on a medium size display.  The layout would have worked (6 images x 2 = 12) but the Cambridge had the `col-md-offset-1` which meant it added up to 13, unlucky for us!

I've fixed it so now the images are centred using the `center-block` css and so that when the page is reduced in size we get 3 images above another 3, and if it is reduced in size further we get 2 above 2 above 2.

Let me know if this is ok.

Thanks

**Comment by AnnaGoodman1** [comment]
brilliant, thanks @nikolai-b - and thanks also for the explanation, I actually care more than you (or I!) might think having spent a bit of time reading about this and trying to work out what was going wrong...

**Comment by Robinlovelace** [comment]
Great work!

**Comment by usr110** [comment]
Sorry Anna. Lately I haven't had the chance to look at pct-issues. So glad Nikolai keeps tab on them - good job!

**Pull request merged**
