### PR TITLE
Revert "Merge pull request #794 from npct/tag-updates"

### PR DESCRIPTION
**Pull request by nikolai-b**
I would prefer master at all times to be ready to merge into production (except that it could do with being tested a bit as some features are hard to test fully locally).  I don't really understand the changes but if they aren't ready for production can we revert them unless they need to be tested on staging?

This reverts commit b3b81ab4cfb22de8cd56f963cc62e51b0e1c7827, reversing
changes made to 442bdbec447f5adc094ab4644e453695cb1b8601.

### CODE REVIEW

**Comment by AnnaGoodman1** [comment]
fine by me to revert

**Comment by AnnaGoodman1** [comment]
I had thought this would restore my old PR tag-update, but it seems not yet - is this possible @nikolai-b ?

**Comment by Robinlovelace** [comment]
> I had thought this would restore my old PR tag-update, but it seems not yet - is this possible

I think we just need to put in a new PR. The branch is still there though, as shown below.

image

**Comment by AnnaGoodman1** [comment]
if you know how to fix it for me @Robinlovelace then please do, I dont know how and on small attempt just get error message about needing to debug its state. Could be same name or new name, just with same commit history and  changes as old PR if possible

**Comment by AnnaGoodman1** [comment]
image

**Comment by Robinlovelace** [comment]
Hi @AnnaGoodman1 sorry this is happening, I suspect it would have been less hassle to switch to master for this work, with the advantage that we'd see the changes on the test server outweighing the disadvantage that master isn't always ready to merge into production. As a potential fix I've created a new branch, `tag-updates2` and opened a new PR: https://github.com/npct/pct-shiny/pull/810/files 

What's strange is that it doesn't track all the files that have changed. @nikolai-b my suggestion would be that we 'rewrite history' to under the commit that reverted the PR and just work from master. If there are other solutions, I'm open to those also. Let me know how you get on with this new branch Anna, info on that can be found here: https://help.github.com/en/desktop/contributing-to-projects/syncing-your-branch

**Comment by AnnaGoodman1** [comment]
thanks @Robinlovelace , I will wait to see what @nikolai-b says. I think we do want a solution that tracks the changed files, otherwise how else can you all do the code review properly?

**Comment by Robinlovelace** [comment]
Hi @AnnaGoodman1 it seems others have had the same issue: https://stackoverflow.com/questions/27852143/how-to-pr-and-merge-again-after-reverting-pr-using-github-revert-button

I'll try to implement the second solution and let you know if it works.

**Pull request merged**
