### PR TITLE
210528 manual page edit

### PR DESCRIPTION
**Pull request by AnnaGoodman1**
small edits requested by James, to update news feed and make it more obvious that the manuals page includes reports too

### CODE REVIEW

**Comment by Robinlovelace** [comment]
This was fine to merge but can you review and approve next time @usr110 ? On holiday so slow to respond, good changes in any case :+1:

**Comment by usr110** [comment]
Noted now. Some how missed that step. Good to remind, @Robinlovelace

**Comment by AnnaGoodman1** [comment]
ok great. when can it go to production?

**Comment by Robinlovelace** [comment]
Good to go I think: https://github.com/npct/pct-shiny/pull/875

**Pull request merged**
