### PR TITLE
HTML tidy

### PR DESCRIPTION
**Pull request by nikolai-b**
I noticed a few of our HTML pages do not have valid HTML :cry: 

I used https://validator.w3.org

### CODE REVIEW

**Comment by Robinlovelace** [comment]
The changes look OK to me, great work @nikolai-b. Are they valid now / how can I check on a local version of the branch?

**Comment by nikolai-b** [comment]
Great question @Robinlovelace , sadly we have no ways of checking the HTML hence getting to that state.  I'd be happy to prioritise looking at this as an issue but I doubt it is something easy to fix.  Most browsers would not complain but using deprecated or invalid syntax could cause some browsers to not be able to view the site. Would you like me to add an issue to Github?

> Are they valid now

It does not make our HTML all valid but it removes some errors.  Might be best to review each commit change separately as then you can see why I've done them, it is just 3 small isolated improvements.

**Comment by Robinlovelace** [comment]
> It does not make our HTML all valid but it removes some errors. Might be best to review each commit change separately as then you can see why I've done them, it is just 3 small isolated improvements.

OK I'll checkout this branch and review as best I can on Firefox. Not my area of expertise but they look like minor changes with clear benefit and no downside so should be fine.

**Comment by Robinlovelace** [comment]
National downloads look fine: 

image

**Comment by Robinlovelace** [comment]
Manual and other html files also look fine in Firefox on this branch.

**Pull request merged**
