### PR TITLE
Update production

### LINKED ISSUE #813: change how lines ordered
James suggests that now that we also monetise sickness absence benefit, we change this sorting by reduction in deaths to sorting by 'health economic benefit' ( physical activity impact on years of life + impact on sickness absence). Seems good to me, I should be able to make those changes this week - okay with @Robinlovelace and @RachelAldred ?
  
Untitled

(note to self, need to update manual b and codebook od_small and all files in Rsmall repo and regional_sha_Rsmall if  we do this)

### PR DESCRIPTION
**Pull request by Robinlovelace**
This will update the data to include the new TAG methods and close #813. Heads-up @nikolai-b

### CODE REVIEW

**Comment by AnnaGoodman1** [comment]
fine by me for this to happen now, if ok with @nikolai-b  too

**Comment by Robinlovelace** [comment]
Please review and merge when you get a chance @nikolai-b, thanks!

**Comment by AnnaGoodman1** [comment]
actually lets wait til outstanding git issue solved

**Comment by nikolai-b** [comment]
@AnnaGoodman1 just so I'm clear we can merge this after #816 is ready (but ideally not before)?

**Comment by AnnaGoodman1** [comment]
yes. As far I am concerned now ready to ad din #816 and then merge...

**Comment by AnnaGoodman1** [comment]
happy for this to merge into production, thank sall

**Comment by AnnaGoodman1** [comment]
@nikolai-b , could you merge this in if happy?

**Comment by Robinlovelace** [comment]
Merging now as agreed with Nikolai. Please @AnnaGoodman1, @JDWoodcock, @RachelAldred, @usr110 and @joeytalbot please check the updated website and report back any issues. @nikolai-b may should be able to do some 'hot fixes' if any emerge but this has been well tested on the test server so not expecting any. Great work all!

**Comment by Robinlovelace** [comment]
Update, this has still not deployed as the CI service is downloading all the new data, as can be seen here: https://circleci.com/gh/npct/pct-shiny/1454?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Robinlovelace** [comment]
Update, latest changes are on production:

image

**Pull request merged**
