### PR TITLE
Highlight polygons using leaflet library

### PR DESCRIPTION
**Pull request by usr110**
Instead of adding highlighted region (polygons) on the fly, add all the regions in the start. 

Covers:
- Simplifies the code
- Highlighting is quicker
- Does not show any highlighted region when the mouse is over the already selected region

Needs to do:
- Set the view of the map when the app starts
- Further testing

### CODE REVIEW

**Comment by usr110** [comment]
Relevant to https://github.com/npct/pct-shiny/issues/545

**Comment by Robinlovelace** [comment]
Sounds great Ali, will test asap.

**Comment by Robinlovelace** [comment]
@usr110 is this ready to test?

**Comment by usr110** [comment]
Yes it is. The only issue I am dealing right now is that zooming doesn't need to change when map layer is changed.

**Comment by usr110** [comment]
@Robinlovelace now everything should be in order. Thanks for testing.

**Comment by Robinlovelace** [comment]
This is excellent work Ali. Accepting it into testing.

**Pull request merged**
