### PR TITLE
region stats

### PR DESCRIPTION
**Pull request by AnnaGoodman1**

### CODE REVIEW

**Comment by AnnaGoodman1** [comment]
hi both, minor correction to the 'z' zone files, and region stats files updated accordingly - if you could merge with production and make live soonish that would be great

**Comment by AnnaGoodman1** [comment]
great, thanks. new numbers 2% to 6% larger on health, I have done a bit of checking and think ok to go live....

**Comment by AnnaGoodman1** [comment]
@Robinlovelace / @nikolai-b , I have just realised this never made it onto even the test server let alone master server. Can we do that please? (cc @JDWoodcock , for info)

**Comment by Robinlovelace** [comment]
Interesting, it does indeed seem that the test server is serving the app at this point: https://github.com/npct/pct-shiny/tree/a5ae5f4

Has something happened to the auto-deploy system Nikolai?

**Comment by AnnaGoodman1** [comment]
@nikolai-b just reminding on this issue... also @usr110 if you happen to know the answer,,,..

ALSO PCT main server currently not working for me, if anyone replicates can we make an issue?

**Comment by JDWoodcock** [comment]
hi all
I can’t get it to launch in firefox but seems ok in chrome

**Comment by Robinlovelace** [comment]
Main site is working fine for me:

image

**Comment by JDWoodcock** [comment]
im struggling to get past front page

**Comment by JDWoodcock** [comment]
oh it did eventually, just slow I think

From: James Woodcock <jw745@medschl.cam.ac.uk>
Sent: 15 July 2020 16:54
To: npct/pct-shiny <reply@reply.github.com>; npct/pct-shiny <pct-shiny@noreply.github.com>
Cc: James Woodcock <jw745@cam.ac.uk>; Mention <mention@noreply.github.com>
Subject: RE: [npct/pct-shiny] region stats (#838)

im struggling to get past front page

**Comment by nikolai-b** [comment]
@AnnaGoodman1 very sorry I missed this.  I've updated staging now so these changes are live and made #842 to try and make this less likely to happen.

**Comment by AnnaGoodman1** [comment]
ok great, can see update on test server but not on live one yet?

**Comment by Robinlovelace** [comment]
I've put in a PR to deploy this to production. Many thanks @nikolai-b for fixing the CI, great work, please merge this as appropriate: https://github.com/npct/pct-shiny/pull/843

**Pull request merged**
