### PR TITLE
Round null

### PR DESCRIPTION
**Pull request by nikolai-b**
Should fix https://github.com/npct/pct-shiny/issues/759#issuecomment-512853445

### CODE REVIEW

**Comment by nikolai-b** [comment]
Agreed but this is bringing the site down.  We can make this change, fix the data, then revert this.  I very much want to fix whatever this issue is upstream but once it brings down production it seems more important that we fix the site.

**Comment by Robinlovelace** [comment]
If you're sure that's the cause. I only checked 1 log file. Have you checked more? Approving in any case as cannot see any downsides. Thanks for clarification.

**Comment by nikolai-b** [comment]
@Robinlovelace found out what this is, when on Cambridge scenario and we change back to commute then the input shiny state can be "cambridge" and "commute" briefly before the "cambridge" scenario is deselected, hence the crash.  I think it is fine to then allow this to ignore NULL otherwise we would have to start messing with observer priority https://shiny.rstudio.com/reference/shiny/latest/observe.html and I'm not keen on that.

**Comment by Robinlovelace** [comment]
Agreed. Good diagnosis.

**Pull request merged**
