### PR TITLE
Use kable for html

### PR DESCRIPTION
**Pull request by Robinlovelace**
This branch show's it's possible to use kable to create the same output.

I've tested this and it works. Note it allows deletion of a total of 11 lines, more clarity and ease of updating and this is just the beginning. Sound good @nikolai-b @audev and @usr110?

The aim is to automate, think more, type less and make life easy.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Thanks for your input on this - trying to remove sprintf but keep getting this bug: `Error in data$All : object of type 'closure' is not subsettable`. Any ideas @usr110 ?

**Comment by Robinlovelace** [comment]
Here's the code that generates this bug:

```
diff --git a/pct-shiny-funs.R b/pct-shiny-funs.R
index f4c522e..d278647 100644
--- a/pct-shiny-funs.R
+++ b/pct-shiny-funs.R
@@ -82,7 +82,9 @@ tableEnd <- '</table></tbody>'
 
 tableCommon <- knitr::kable(data.frame(
   Attribute = c("Total commutes: ", "Cyclists (recorded): ", "Cyclists (scenario): "),
-  Value = c("%s","%s (%s%%)" , "%s")), "html")
+  Value = c(data$All, data$Bicycle,
+            paste0(round(100 * data$Bicycle / data$All),
+            round(data[[dataFilter(scenario, "slc")]]) ))), "html")
 
 # Remove SLC and SIC for the 'olc' scenario (recorded)
 tableOLC <- '<tr>
@@ -117,8 +119,7 @@ straightPopup <- function(data, scenario){
                     <td> Distance (km) </td>
                     <td> %s </td>
                     </tr>'),
-                     data$All, data$Bicycle,round(100 * data$Bicycle / data$All),
-                     round(data[[dataFilter(scenario, "slc")]]), round(data$dist, 1))
+                     round(data$dist, 1))
             }
 
     paste(tableStart,tableInterm,tableEnd)
@@ -165,9 +166,8 @@ routePopup <- function(data, scenario){
     tableInterm <- sprintf(paste(
                           tableCommon,
                           blob),
-                          data$All, data$Bicycle, round(100 * data$Bicycle / data$All),
-                          round(data[[dataFilter(scenario, "slc")]]),
-                          round(data$length, 1),round(data$time / 60, 1), round(data$av_incline*100, 1),
+                          round(data$length, 1),
+                          round(data$time / 60, 1), round(data$av_incline * 100, 1),
                           routeTypeLabel[[data$plan[1]]])
 
   }
```

**Comment by usr110** [comment]
@Robinlovelace Could be wrong, but do make sure that the variable exists in the data first. If I remember correctly this error comes up when either the variable doesn't exist or its value is NULL.

**Comment by Robinlovelace** [comment]
Thanks and agreed. But the data *does* exist as the results are correct in the current version of the code on this branch (tested).

**Comment by usr110** [comment]
So you've made sure that data has variables such as data$Bicycle and data$dist etc, so that's great. 
I am afraid I can't offer any other advice then.

**Comment by Robinlovelace** [comment]
I suspect it's related to context. In any case it's bad practice to use `data` as an object names as it's also a function (try `data()`). Not sure if this is causing the problem but can we change the name?

**Comment by usr110** [comment]
Have just cloned the branch and it seems to be working fine. Did you commit the changes where the error was appearing? Also in terms of data, I am assuming you are using pct-data. Is that true?

**Comment by Robinlovelace** [comment]
@usr110 Yes I'm using pct-data for the data. Cheers for merging and testing. Clarification: I'm only getting the bug when replacing `sprintf` with adding the name directly, e.g. from above:

```
-  Value = c("%s","%s (%s%%)" , "%s")), "html")
+  Value = c(data$All, data$Bicycle,
+            paste0(round(100 * data$Bicycle / data$All),
+            round(data[[dataFilter(scenario, "slc")]]) ))), "html")
```

Make sense?

**Comment by usr110** [comment]
@Robinlovelace Thanks for the clarification. The issue is: you are trying to use the data variable outside the popup functions (such as straightPopup and routePopup). tableCommon is kind of a function whose value come from the 'data' variables in these two popups function. So in other words, you can't replace %s with data variables like that.

**Comment by Robinlovelace** [comment]
Aha I see. Any ideas how we can use the data variables directly? I'm thinking that calling the variables where they are used is a good solution that is easy for others to understand and maintain.

**Comment by usr110** [comment]
It is already being done that way - though indirectly, I must say. See this line:

https://github.com/npct/pct-shiny/blob/use-kable-for-html/pct-shiny-funs.R#L116

Just replace tableCommon with kable code there. Remember to replace the same at this line as well:

https://github.com/npct/pct-shiny/blob/use-kable-for-html/pct-shiny-funs.R#L166

**Comment by Robinlovelace** [comment]
Thanks for the hint @usr110 - can you implement this please?

**Comment by usr110** [comment]
@Robinlovelace Sorry but have other commitments, so can't. You might want to leave it for now. 
One more thing, I haven't merged the branches, so please do merge them - again please after testing the code out.

**Comment by audev** [comment]
I can give this a try + new labels as per doc, when I finish with GM data. Planned to release it end of today. Sounds OK?

**Comment by Robinlovelace** [comment]
@audev this sounds great - thanks for working on it!

**Pull request merged**
