### PR TITLE
temporary fix for https://github.com/npct/pct-shiny/issues/621

### PR DESCRIPTION
**Pull request by AnnaGoodman1**
warning users about the 'csv download of firefox' issue

### CODE REVIEW

**Comment by nikolai-b** [comment]
Up to you but we could also use `$.browser.mozilla` to display the warning for FF users only?

**Comment by Robinlovelace** [comment]
I think it's good to warn all users, so they know if they try on a different computer or with someone who uses FF not to be afraid.

**Comment by AnnaGoodman1** [comment]
@nikolai-b , if it is easy to make that sentence firefox specific then to me that would seem a bit better - reduces the amount of text non FF people have to read...

**Comment by Robinlovelace** [comment]
Everyone should see the same text in the download tabs. I feel pretty strongly about that (as strongly as you can for such a minor issue ; ).

**Comment by Robinlovelace** [comment]
I've checked the text and I think it's a clear improvement that will benefit all users. The mention of filenames also minimises ambiguity. This has no side-effects so merging. Can think about browser specific messages later down the line if there's demand or if people feel strongly that the html should vary from computer to computer (which I cannot imagine).

**Comment by nikolai-b** [comment]
I disagree, I think as different browsers do different things and as such we should only show the warning when relevant but as you feel strongly (and I don't) then we can leave it as it is.

**Pull request merged**
