### PR TITLE
Update production - with loading spinner

### PR DESCRIPTION
**Pull request by Robinlovelace**
Planning to merge this on Monday. Heads up @nikolai-b @AnnaGoodman1 @usr110 and @JDWoodcock and @RachelAldred - opportunity to test any small fixes or delay if needs be.

The main improvement from the user's perspective is the loading spinners demonstrated here: #640

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @nikolai-b this seems to be crashing the test server.

**Comment by usr110** [comment]
Good find @Robinlovelace 
Here's the error

```Warning: Error in : 'showElement' is not an exported object from 'namespace:shinyjs'
Stack trace (innermost first):
    58: getExportedValue
    57: ::
    56: observerFunc [/var/shiny/pct-shiny/regions_www/m/server.R#242]
     1: runApp
Warning: Error in : 'showElement' is not an exported object from 'namespace:shinyjs' 
```

It seems the `shinyjs` library needs to be updated.

**Comment by Robinlovelace** [comment]
Well spotted Ali - I guess you're right.

Please take a look and update the pkgs if that seems like the right solution Nikolai.

**Comment by nikolai-b** [comment]
Fixed,

https://github.com/daattali/shinyjs/blob/master/NEWS.md#shinyjs-09

The test server had version 0.8 but both prod servers have 0.9.

I'm going to look at getting packrat working again as this is a silly situation...

**Comment by Robinlovelace** [comment]
OK great stuff. I assume there are no objections to this being merged to production then.

**Comment by nikolai-b** [comment]
If the academic team happy then I'm more than happy for this to be merged.

**Pull request merged**
