### PR TITLE
Tag updates

### PR DESCRIPTION
**Pull request by AnnaGoodman1**
not for merging yet, anna WIP

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Let us know when this is good to go onto the test server and we can merge. Seems there are merge conflicts, which I'm happy to resolve.

**Comment by AnnaGoodman1** [comment]
thanks @Robinlovelace . NB Still NOT FOR MERGING as waiting to finalise various bits of this based on DfT feedback. Just did PR so others could see it

**Comment by Robinlovelace** [comment]
Great, thanks for the update Anna.

**Comment by Robinlovelace** [comment]
Hi @AnnaGoodman1 do you have an ETA when this branch will be good to review/merge?

**Comment by AnnaGoodman1** [comment]
waiting on some global burden of disease numbers from Ali, then soon after that. Hopefully in next week or two

**Comment by Robinlovelace** [comment]
Great, thanks Anna.

**Comment by Robinlovelace** [comment]
Hi @AnnaGoodman1, apologies for merging prematurely. I thought it was a single commit PR separate from the main one, but now realise all of the TAG update commits are in this PR. Apologies. 2 options: 1) revert it; 2) continue on master. Thoughts @usr110 and @nikolai-b also welcome.

**Comment by AnnaGoodman1** [comment]
Oh dear, whoops.  Happy for @usr110 (and @nikolai-b if back from paternity leave) to advise what best to do. 

I will be actively working on these tag updates over the next week, would have planned to ask for code review in 4-7 days. Happy for one of you to revert, or to continue on master, whichever less error prone.  If we could decide in the next day or two that would be great, I will hold off doing more on this until then.

**Comment by AnnaGoodman1** [comment]
> 
> 
> Great to see this new blog post, we should get this up there asap. Thank you @AnnaGoodman1 .

Yes, but it is only published private now, the work is not yet done!

**Comment by Robinlovelace** [comment]
Reverting and continuing on this branch seems to be preferred. Branches are good, sorry again! Thanks for quick PR @nikolai-b.

**Pull request merged**
