### PR TITLE
Fix deadlinks and tidy html

### LINKED ISSUE #855: Link of organizations uses a dead link on accessibility statement
Screenshot_2020-09-24 The Propensity to Cycle Tool Accessibility Statement

All three links point to https://www.pct.bike/tabs/about.html which doesn't exist

Was that intended?

### PR DESCRIPTION
**Pull request by Robinlovelace**
Close #855

### CODE REVIEW

**Comment by Robinlovelace** [comment]
I'm not 100% sure what the `accessibility_body.html` file was doing so have deleted it - did not seem to be linked to Jekyll. Was that an artifact of previous work @nikolai-b ?

**Review by usr110 — COMMENTED** [review]
Now seems to work fine; just tested it. Thanks @Robinlovelace for the fix. Great work!

One minor request, if I may (not related to this fix): would be nice if all external links are opened in a new tab. What do you think?

**Comment by usr110** [comment]
Also is this file https://github.com/npct/pct-shiny/blob/deadlinks-1/regions_www/tabs/accessibility.html
being used?

**Comment by Robinlovelace** [comment]
> One minor request, if I may (not related to this fix): would be nice if all external links are opened in a new tab. What do you think?


Agreed. Unless @nikolai-b or anyone else disagrees, I'm in favour, especially after reading [this](https://uxmovement.com/navigation/why-external-links-should-open-in-new-tabs/).

**Comment by Robinlovelace** [comment]
> Also is this file https://github.com/npct/pct-shiny/blob/deadlinks-1/regions_www/tabs/accessibility.html
> being used?

Good question. It seems it's a duplicate of this:

https://github.com/npct/pct-shiny/blob/deadlinks-1/regions_www/accessibility.html

Was that duplication intended with #851 @nikolai-b ?

**Comment by Robinlovelace** [comment]
Updated response @usr110 (also cc @nikolai-b supporting Jekyll):

> Also is this file https://github.com/npct/pct-shiny/blob/deadlinks-1/regions_www/tabs/accessibility.html
being used?

I think it is now, in the app.

**Comment by nikolai-b** [comment]
I was planning on making the accessibility work from inside the shiny app, i.e. 
http://npct0.vs.mythic-beasts.com/m/?r=isle-of-wight click the about tab then the Accessibility Statement then your taken out of the app.  I was thinking of doing something clever using `regions_www/tabs/accessibility.html` and `regions_www/tabs/accessibility_body.html` but it only works if the Accessibility Statement is in the nav and now it isn't so :shrug:.  Both these files can be removed, thanks for spotting!

@usr110 are you able to get Jekyll working locally?  No worries if not just that I've added a whole new tool and wanted to offer support it get it running if you need it.

**Comment by Robinlovelace** [comment]
@nikolai-b do you want to get the accessibility statement working in the app? I suggest it's not worth it.

**Comment by nikolai-b** [comment]
When it was in the nav I was going to (only a few minutes work) hence those files. No going to now. 

P.S. I thought all the external links do open in a new tab.

**Comment by Robinlovelace** [comment]
Thanks for the clarification @nikolai-b. Looking forward to a review this PR and, further fixes (I think external links is worth opening as a separate issue) and seeing #855 fixed on production soon. Good work on identifying, communicating and fixing issues in progress!

**Comment by usr110** [comment]
> I was planning on making the accessibility work from inside the shiny app, i.e.
> http://npct0.vs.mythic-beasts.com/m/?r=isle-of-wight click the about tab then the Accessibility Statement then your taken out of the app. I was thinking of doing something clever using `regions_www/tabs/accessibility.html` and `regions_www/tabs/accessibility_body.html` but it only works if the Accessibility Statement is in the nav and now it isn't so 🤷. Both these files can be removed, thanks for spotting!

Great, thanks for the explanation. Can't we embed the whole statement as part of the `about` page? (Shared similar thoughts here: https://github.com/npct/pct-shiny/issues/848#issuecomment-698258721)

> @usr110 are you able to get Jekyll working locally? No worries if not just that I've added a whole new tool and wanted to offer support it get it running if you need it.

After installing I followed the steps from here: https://github.com/npct/pct-shiny/blob/master/jekyll-static/README.md 

it failed with 

> $ jekyll s -d ../regions_www
> Traceback (most recent call last):
>         10: from C:/Ruby27-x64/bin/jekyll:23:in `<main>'
>          9: from C:/Ruby27-x64/bin/jekyll:23:in `load'
>          8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/exe/jekyll:11:in `<top (required)>'
>          7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
>          6: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler.rb:149:in `setup'
>          5: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:26:in `setup'
>          4: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:26:in `map'
>          3: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/spec_set.rb:147:in `each'
>          2: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/spec_set.rb:147:in `each'
>          1: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:31:in `block in setup'
> C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:312:in `check_for_activated_spec!': You have already activated em-websocket 0.5.2, but your Gemfile requires em-websocket 0.5.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)

P.S. I am completely new to Jekyll, so might be making a very basic error.

**Comment by Robinlovelace** [comment]
@usr110 it failed first time for me too but worked eventually. BTW please can you review the PR, want to get the fix on production ASAP. We can tidy up later but atm there are deadlinks on the pct.bike which need fixing. :fire:  :fire_engine:

**Comment by usr110** [comment]
> 
> 
> @usr110 it failed first time for me too but worked eventually. BTW please can you review the PR, want to get the fix on production ASAP. We can tidy up later but atm there are deadlinks on the pct.bike which need fixing. 🔥 🚒

Understandable!

Re the fix, I think I've okayed it. Would you like to resolve opening the links in a new tab first or should we create another PR for it?

These are the two links:

Screenshot_2020-09-25 The Propensity to Cycle Tool Accessibility Statement(1)
Screenshot_2020-09-25 The Propensity to Cycle Tool Accessibility Statement

**Review by usr110 — APPROVED** [review]

**Comment by Robinlovelace** [comment]
> Would you like to resolve opening the links in a new tab first or should we create another PR for it?

Create a new PR I say to keep things modular and get this hotfix in.

**Pull request merged**
