### PR TITLE
Update outputs_regional_sha

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by AnnaGoodman1** [comment]
great,  but don't merge yet as only half the new files up updated

**Comment by AnnaGoodman1** [comment]
now ready to merge I think

**Comment by usr110** [comment]
Thanks @AnnaGoodman1 (and @Robinlovelace for creating the issue).
I have just tested this for `London`, and it seems to work fine. So good job @AnnaGoodman1

**Comment by Robinlovelace** [comment]
Great. Thanks @usr110 for approving, merging and testing! Next step: deploy I guess. Heads-up @nikolai-b - is this good to go from your perspective? There are a few PRs we should complete and I'm interested in which order to go for - suspect merging all onto master and then PR into production will be best.

**Pull request merged**
