### PR TITLE
Try packrat

### PR DESCRIPTION
**Pull request by nikolai-b**
Not sure if this will work on the servers as I don't fully understand how packrat installs on other systems but I'd like to try it out.

### CODE REVIEW

**Comment by nikolai-b** [comment]
I'm not sure.  There have been many instances of us developing on one version, our test server on another version (or something missing), and our production servers being on an entirely different version (or with also packages missing).

Most were resolved without Github but there are a few I could find:

https://github.com/npct/pct-shiny/pull/641#issuecomment-341678983
https://github.com/npct/pct-shiny/issues/598
https://github.com/npct/pct-shiny/pull/479#issuecomment-264885060

@usr110 and @AnnaGoodman1 how do you feel about fixing the packages for development, staging and production?  Not really sure why it would make the repo unwieldy, it would mean that new users would be using the same versions, surely a more wieldy (if there is such a word)...

**Comment by Robinlovelace** [comment]
It means that for testing we'd have to pull down loads of external files, making it harder to test new features made possible by package updates. Your spinners are a case in point: constrained but the previous versions of packages potential improvements are not clear.

And by unwieldy I just mean the download size will increase further. No biggy but in general I'm against having loads of large binaries in a repo, especially when they're available from elsewhere.

**Comment by nikolai-b** [comment]
@Robinlovelace fair point, you don't want to add the binaries, there is a discussion about that here: 
https://github.com/rstudio/packrat/issues/59

The issue is that people can remove a release from CRAN and if we don't included the binaries then if someone does that to a package version we use than it will brake our app.  I think it is unlikely but with npm (a JavaScrip package manager) I've been hit by this exact problem https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/ hence the binaries.

I've rebased and removed them but just thought I'd explain my rational.  Maybe I'm understanding R and packrat incorrectly though but normally in software pining versions is a very good idea.

**Comment by Robinlovelace** [comment]
One to discuss on the ☎️  lots going on and can understand the reasoning but still think on balance the +s do not outweigh the -s for reasons that are best chatted over.

**Comment by usr110** [comment]
I really like the idea of it and fair points @nikolai-b. In my view @Robinlovelace would be better to discuss here.

**Comment by Robinlovelace** [comment]
Sure. I think this may be worth re-considering with recent acceleration in changes affecting many parts of the R ecosystem, some of which could affect this project. Of note, work has re-commenced on Rstudio/leaflet: https://github.com/rstudio/leaflet and the lead developer Joe Cheng is asking users to test the development version for breaking changes before submitting a new version to CRAN. As discussed the + is that this will help control exactly when new packages are updated. The - is additional complexity and download sizes.

@nikolai-b what are your latest views on this given that this PR is a few months old? I'm certainly happy to consider it now major changes are unlikely for a while after the successful deployment of the updates for Wales (great work on that).

@usr110 happy for discussion to happen here - what are your views on this?

**Comment by nikolai-b** [comment]
To check the version of R packages on the servers I have to:
* lookup how to print R package version info
* log into the test server and check package version
* log into both production servers and do the same

This is a manual process that has gone wrong a few times.  With https://github.com/npct/pct-shiny/pull/659#issue-178049209 I need to check the shiny version.

If we had packrat we'd all be using the same shiny version and if we need to update it then it'd be updated for each of all of us and also when we deploy so everything would always be in sync.  

I don't really understand your issue with download size, why does it matter?  The data files are much bigger and if you want to test it locally you'd have to install the packages one way or another.  Doing it this way means you are guaranteed to install the correct versions. Currently you could try run the repo with different package versions and it may or may not work, that to me is complexity.

**Comment by Robinlovelace** [comment]
Strong arguments @nikolai-b I just wasn't sure that it was actually working. I've limited time this week but can test and give proper feedback on this next week when I'm back from Germany. @usr110 what are your views on this? Grateful if you could test and provide a third opinion and feedback from testing if you have time later in this week or early next week. Cheers for pushing on this Nikolai and sorry it's not been working to plan - agree changes upstream can lead to things failing as we've learned the hard way with the Geocomputation with R book project, as you'll see from the Travis build history (we're deliberately using the latest CRAN version and in some cases the dev versions to ensure the content is up-to-date, something that does not matter so much with the PCT although it will still be good for the code to evolve with new packages to support new users over the coming years who are unlikely to have old package versions): https://travis-ci.org/Robinlovelace/geocompr/builds

**Comment by usr110** [comment]
Fully endored @nikolai-b points here. Just tested it and it seems to work quite fine @Robinlovelace 
The only downsides are these initial downloads takes time - took over 10 minutes (but of course this is not a routine task), and all the installed libraries are of course repo (or project) specific (as they are installed in a sub-folder `packrat/lib`); this means the libraries won't be shared system-wide (but that's by design, I believe).

**Comment by Robinlovelace** [comment]
Cheers for the feedback Ali. It seems like a balance between reproducibility / ease or set-up on the one hand and stability on the other. Given that the PCT is primarily used as an online service I'm happy for this to happen, pending on an up-to-date R system. I'll test it on this docker image now on my work desktop: https://hub.docker.com/r/robinlovelace/geocompr/builds/

**Comment by Robinlovelace** [comment]
Update: it seems to be doing something on my dockerized version of R, running on RStudio server in the browser:

image

**Comment by Robinlovelace** [comment]
Happy to say the test worked. Eventually. I had to manually install the `sp` package. @nikolai-b does that need adding to packrat. Otherwise very happy with this, good to go I think, and is not so bad for reproducibility, users will just have to be warned that they'll need sufficient HD space (a few 100 MB perhaps - any ideas exactly how much?) to install a veritable kitchen sink of old R packages!

**Comment by Robinlovelace** [comment]
Obligatory screenshot of it working (plus install messages from `sp` install on the left):

image

**Comment by Robinlovelace** [comment]
Here's the error message I got running from a virgin install on that docker image (based on Ubuntu + R  3.4.4 - you may want to rebuild this packrat snaphot on an up-to-date version of R, unless there is a good reason to not upgrade base R either (see the line `  The most recent snapshot was generated using R version 3.3.3`):

```
Packrat mode on. Using library in directory:
- "/data/pct-shiny/packrat/lib"
> 
> shiny::runApp("regions_www/m/")
Loading required package: shiny

Listening on http://127.0.0.1:6637

Attaching package: ‘shinyjs’

The following object is masked from ‘package:shiny’:

    runExample

The following objects are masked from ‘package:methods’:

    removeClass, show

[1] "Fetching regional data"
Warning: Error in : package or namespace load failed for ‘sp’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘lattice’
Stack trace (innermost first):
    45: value[[3L]]
    44: tryCatchOne
    43: tryCatchList
    42: tryCatch
    41: FUN
    40: lapply
     1: shiny::runApp
Error : package or namespace load failed for ‘sp’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘lattice’
In addition: Warning message:
In packrat::restore(prompt = FALSE, restart = TRUE) :
  The most recent snapshot was generated using R version 3.3.3
From https://github.com/npct/pct-outputs-regional-R
   b9da04b..77c6003  master     -> origin/master
[1] "Fetching regional data"
Warning: Error in : package or namespace load failed for ‘sp’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘lattice’
Stack trace (innermost first):
    45: value[[3L]]
    44: tryCatchOne
    43: tryCatchList
    42: tryCatch
    41: FUN
    40: lapply
     1: shiny::runApp
Error : package or namespace load failed for ‘sp’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘lattice’

> install.packages("lattice")
Installing package into ‘/data/pct-shiny/packrat/lib/x86_64-pc-linux-gnu/3.4.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/lattice_0.20-35.tar.gz'
Content type 'application/x-gzip' length 359813 bytes (351 KB)
==================================================
downloaded 351 KB

Error: package or namespace load failed for ‘stats’ in get(Info[i, 1], envir = env):
 cannot open file '/data/pct-shiny/packrat/lib-R/stats/R/stats.rdb': No such file or directory
During startup - Warning message:
package ‘stats’ in options("defaultPackages") was not found 
Error: package ‘compiler’ does not have a namespace
Execution halted
Warning in install.packages :
  installation of package ‘lattice’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpAG0nFL/downloaded_packages’
> shiny::runApp("regions_www/m/")

Listening on http://127.0.0.1:6637
[1] "Fetching regional data"
Warning: Error in : package or namespace load failed for ‘sp’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘lattice’
Stack trace (innermost first):
    45: value[[3L]]
    44: tryCatchOne
    43: tryCatchList
    42: tryCatch
    41: FUN
    40: lapply
     1: shiny::runApp
Error : package or namespace load failed for ‘sp’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘lattice’
```

After this it worked though:

```r
install.packages("sp")
```

**Comment by Robinlovelace** [comment]
Update: yep just a shade over 100 Mb in there. Not too bad by todays standards, will just have to remember this we ever do more hackathons based on this repo (or we could create another `no-packrat` or `dev` branch). But overall, pending the **sp** issue and question about which R version to use (is it easy to specify on install?) this PR gets a 👍 from me now.

**Comment by Robinlovelace** [comment]
image

**Comment by Robinlovelace** [comment]
Another suggestion I just thought of @nikolai-b: update all R versions and pkgs now (good timing before Phase III), fix any issues arising (guarantee it won't be too hard with our dev team!) and then re-generate packrat pinned to a more recent (and slightly more computationally efficient) version of R. Sound good?

**Comment by Robinlovelace** [comment]
Update on R versions: seems R 3.5.0 has some major changes that will benefit our project - see here: https://www.r-bloggers.com/big-changes-behind-the-scenes-in-r-3-5-0/

**Comment by Robinlovelace** [comment]
@nikolai-b any update on this? Suggest we try this after the schools layer is up. Cheers.

**Comment by Robinlovelace** [comment]
packrat has been superseded by renv https://github.com/rstudio/renv suggest we use that if we revive the idea.

Closing for now.

**Pull request closed without merging**
