### PR TITLE
Update production

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
To be merged after https://github.com/npct/pct-shiny/pull/827

**Comment by Robinlovelace** [comment]
Hey @AnnaGoodman1 can you try again on the test server? In other news, the landing page is looking good on the test server now:

image

**Comment by AnnaGoodman1** [comment]
ok yes, the firefox crtl + S issue seems sorted. great!

**Comment by AnnaGoodman1** [comment]
But please do still add back in:

        <p>Please be aware that equivalent files for different purposes and geographies have <b>the same file name</b> when downloaded (e.g. ‘z_all.geojson’ for both the MSOA and LSOA national zones files).  To avoid confusion you may want to rename those files or save them in labelled folders. Note also that when <b>downloading 'csv' files using a Firefox browser</b>, the file will open onscreen in a new webpage.  If you then type "Ctrl + S" the onscreen data will download as a csv file.</p>

**Comment by AnnaGoodman1** [comment]
oh ok and I see that actually names have been changed so inside the file itself. wow, great. so my previous comment maybe redundant.

**Pull request merged**
