### PR TITLE
School tiles

### PR DESCRIPTION
**Pull request by nikolai-b**
This adds the school tiles.  I've unimaginatively named the Cycling Flow:
"Route Network (Tiles)"

Is the: 
"Route Network (LSOA, Clickable)"
relevant?

This also updates the regional data so the school purpose is shown on all regions.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Great work @nikolai. I plan to test this locally tomorrow and accept if it works.

**Comment by nikolai-b** [comment]
@Robinlovelace great.  Note that with https://github.com/mem48/pct-raster-tests/issues/4 still live the tiles mask our base map but that will be easy to fix.

**Comment by Robinlovelace** [comment]
@nikolai-b tested. works. shown below for Southampton. Lets see if this deploys on the test server...

image

**Comment by Robinlovelace** [comment]
image

**Comment by Robinlovelace** [comment]
@nikolai-b in answer to your question: yes I think the 'clickable' bit is relevant but not essential.

**Pull request merged**
