### PR TITLE
Release

### PR DESCRIPTION
**Pull request by nikolai-b**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
@nikolai-b any UI changes? Please merge if so!

**Comment by usr110** [comment]
This issue still exists on the live server:

https://github.com/npct/pct-shiny/issues/495

but since @nikolai-b fixed it, I believe, we should merge. Especially with the removal of all the hacks (https://github.com/npct/pct-shiny/commit/25f6f235d0d3f4d66de0cea8aa91105100ff17a5)(great work @nikolai-b, btw), it should work on the live server.

**Comment by Robinlovelace** [comment]
Thanks Ali. Please double check on the live server. Great to see all those fixes go live.

**Comment by Robinlovelace** [comment]
*production server I mean.

**Comment by usr110** [comment]
Already looking into it, Robin. It seems the front-page map links are not working on the 'live' server for some reason.

**Comment by Robinlovelace** [comment]
Cheers for testing. That's quite a big issue.

**Comment by Robinlovelace** [comment]
Was just a matter of the server updating I think, check this: http://www.pct.bike/cumbria/

**Comment by Robinlovelace** [comment]
Any other issues spotted?

**Comment by usr110** [comment]
no, not really. Had reverted all the recent merges I made. @nikolai-b will update the production branch.

**Comment by Robinlovelace** [comment]
OK - please re-open the pull request and we'll wait for @nikolai-b to accept it, as suggested.

**Pull request merged**
